-- MySQL Script generated by MySQL Workbench
-- Sun 01 Sep 2019 12:53:29 AM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imagen` (
  `idimagennombre` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `imagencol` BIGINT(12) NULL,
  `pixel` BLOB(25) NULL,
  PRIMARY KEY (`idimagennombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escritor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escritor` (
  `codigo_escritor` INT NOT NULL,
  `sobre_nombre` VARCHAR(10) NULL,
  PRIMARY KEY (`codigo_escritor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carta` (
  `codigo_carta` INT NOT NULL,
  `cartacol` VARCHAR(45) NULL,
  `imagen_idimagennombre` INT NULL,
  `escritor_codigo_escritor` INT NOT NULL,
  PRIMARY KEY (`codigo_carta`),
  INDEX `fk_carta_imagen_idx` (`imagen_idimagennombre` ASC) VISIBLE,
  INDEX `fk_carta_escritor1_idx` (`escritor_codigo_escritor` ASC) VISIBLE,
  CONSTRAINT `fk_carta_imagen`
    FOREIGN KEY (`imagen_idimagennombre`)
    REFERENCES `mydb`.`imagen` (`idimagennombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carta_escritor1`
    FOREIGN KEY (`escritor_codigo_escritor`)
    REFERENCES `mydb`.`escritor` (`codigo_escritor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escritor_has_carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escritor_has_carta` (
  `escritor_codigo_escritor` INT NOT NULL,
  `carta_codigo_carta` INT NOT NULL,
  PRIMARY KEY (`escritor_codigo_escritor`, `carta_codigo_carta`),
  INDEX `fk_escritor_has_carta_carta1_idx` (`carta_codigo_carta` ASC) VISIBLE,
  INDEX `fk_escritor_has_carta_escritor1_idx` (`escritor_codigo_escritor` ASC) VISIBLE,
  CONSTRAINT `fk_escritor_has_carta_escritor1`
    FOREIGN KEY (`escritor_codigo_escritor`)
    REFERENCES `mydb`.`escritor` (`codigo_escritor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escritor_has_carta_carta1`
    FOREIGN KEY (`carta_codigo_carta`)
    REFERENCES `mydb`.`carta` (`codigo_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta` (
  `codigo_respuesta` INT NOT NULL,
  `respuesta` VARCHAR(100) NULL,
  `carta_codigo_carta` INT NOT NULL,
  PRIMARY KEY (`codigo_respuesta`),
  INDEX `fk_respuesta_carta1_idx` (`carta_codigo_carta` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_carta1`
    FOREIGN KEY (`carta_codigo_carta`)
    REFERENCES `mydb`.`carta` (`codigo_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;